global XSMIN_HARD_LIMIT
global XSMAX_HARD_LIMIT
global YSMIN_HARD_LIMIT
global YSMAX_HARD_LIMIT
global ZSMIN_HARD_LIMIT
global ZSMAX_HARD_LIMIT
global XOMIN_HARD_LIMIT
global XOMAX_HARD_LIMIT
global YOMIN_HARD_LIMIT
global YOMAX_HARD_LIMIT
global ZOMIN_HARD_LIMIT
global ZOMAX_HARD_LIMIT

XSMIN_HARD_LIMIT = -1000
XSMAX_HARD_LIMIT = 1000
YSMIN_HARD_LIMIT = -1000
YSMAX_HARD_LIMIT = 1000
ZSMIN_HARD_LIMIT = -1000
ZSMAX_HARD_LIMIT = 1000
XOMIN_HARD_LIMIT = -1000
XOMAX_HARD_LIMIT = 1000
YOMIN_HARD_LIMIT = -1000
YOMAX_HARD_LIMIT = 1000
ZOMIN_HARD_LIMIT = -1000
ZOMAX_HARD_LIMIT = 1000

global XSMIN_SOFT_LIMIT
global XSMAX_SOFT_LIMIT
global YSMIN_SOFT_LIMIT
global YSMAX_SOFT_LIMIT
global ZSMIN_SOFT_LIMIT
global ZSMAX_SOFT_LIMIT
global XOMIN_SOFT_LIMIT
global XOMAX_SOFT_LIMIT
global YOMIN_SOFT_LIMIT
global YOMAX_SOFT_LIMIT
global ZOMIN_SOFT_LIMIT
global ZOMAX_SOFT_LIMIT

XSMIN_SOFT_LIMIT = -1000
XSMAX_SOFT_LIMIT = 1000
YSMIN_SOFT_LIMIT = -1000
YSMAX_SOFT_LIMIT = 1000
ZSMIN_SOFT_LIMIT = -1000
ZSMAX_SOFT_LIMIT = 1000
XOMIN_SOFT_LIMIT = -1000
XOMAX_SOFT_LIMIT = 1000
YOMIN_SOFT_LIMIT = -1000
YOMAX_SOFT_LIMIT = 1000
ZOMIN_SOFT_LIMIT = -1000
ZOMAX_SOFT_LIMIT = 1000

global XS_BACKLASH
global YS_BACKLASH
global ZS_BACKLASH
global XO_BACKLASH
global YO_BACKLASH
global ZO_BACKLASH

XS_BACKLASH = 0
YS_BACKLASH = 0
ZS_BACKLASH = 0
XO_BACKLASH = 0
YO_BACKLASH = 0
ZO_BACKLASH = 0

global XS_BASE_POSITION
global YS_BASE_POSITION
global ZS_BASE_POSITION
global XO_BASE_POSITION
global YO_BASE_POSITION
global ZO_BASE_POSITION

XS_BASE_POSITION = 0
YS_BASE_POSITION = 0
ZS_BASE_POSITION = 0
XO_BASE_POSITION = 0
YO_BASE_POSITION = 0
ZO_BASE_POSITION = 0

global XS_RELATIVE_POSITION
global YS_RELATIVE_POSITION
global ZS_RELATIVE_POSITION
global XO_RELATIVE_POSITION
global YO_RELATIVE_POSITION
global ZO_RELATIVE_POSITION

XS_RELATIVE_POSITION = 0
YS_RELATIVE_POSITION = 0
ZS_RELATIVE_POSITION = 0
XO_RELATIVE_POSITION = 0
YO_RELATIVE_POSITION = 0
ZO_RELATIVE_POSITION = 0